{
"作者":"",
"站名":"6v电影",
"请求头": "",
"调试":"",
//"起始页": "",
"图片代理": "1",
"分类url":"https://www.66s6.net/{cateId}/index_{catePg}.html[firstPage=https://www.66s6.net/{cateId}/index.html]",//[firstPage=https://www.66s6.net/{cateId}/index.html]}加在后面可以去掉起始页项
"分类":"喜剧片$xijupian#动作片$dongzuopian#科幻片$kehuanpian#恐怖片$kongbupian#爱情片$aiqingpian#纪录片$jilupian#动画片$donghuapian#剧情片$juqingpian#战争片$zhanzhengpian#电视剧$dianshiju#综艺$zongyi",
"主页url":"https://www.66s6.net",
"数组":"<div class=\"post_hover\">&&<div class=\"info\">",
"图片":"<img src=\"&&\"",
//"标题":"影片信息\">&&</div>",
"链接":"href=\"&&\"",
//"副标题":"<div class=\"movie-rating cor4\">&&</div>",
"搜索模式":"1",
"搜索图片":"data-original=\"&&\"",
"搜索标题":"影片信息\">&&</div>",
"搜索链接":"href=\"&&\"",
"搜索后缀":"/v/",
//"线路数组":"<td style=\"word-break&&</a>",
//"二次截取":"<div class="clear">&&<div class=\"navigation container\"",
//"线路标题":">&&</a>",
"播放数组": "<div class=\"clear\">&&<div class=\"navigation container\">",
//"播放二次截取": "<div class=\"clear\">&&<div class=\"navigation container\"",
//"播放列表": "<a title&&</a>",
//"播放标题":">&&</a>",
//"播放链接":"href=\"&&\"",
"影片类型":"<div class=\"scroll-content\">&&</p>",
"导演":"导演：&&</div>",
"主演":"演员：&&</div>",
"简介":"<div class=\"summary detailsTxt\"&&</div>",
"免嗅":"0",
"嗅探词":".m3u8#.mp4",
"过滤词":".jpg#.png#.ico#.gif"
}